name: Python application

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container: amitshalev/angular_flask:latest

    steps:     
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Test with pytest
        run: |
          npm install
          npm run build
          npm test
          ls
      -
        name: push
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish'
          force-add: 'true'
          files: dist/
          name: amitshalev
          email: amit30005@gmail.com


