name: Python application

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container: amitshalev/angular_flask:latest

    steps:
    - uses: actions/checkout@v1
    - name: Test with pytest
      run: |
        npm install
        npm test
    - name: Archive production artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          dist
