name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: amitshalev/angular_flask:latest

    steps:
    - name: Test with pytest
      run: |
        npm test




