name: Python application

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container: amitshalev/angular_flask:latest

    steps:
    - uses: actions/checkout@v1
    - name: Test with pytest
      run: |
        ls
        npm test




